apiVersion: batch/v1
kind: Job
metadata:
  name: yunikorn-cleanup
  namespace: {{ .Release.Namespace }}
  annotations:
    "helm.sh/hook": post-delete
    "helm.sh/hook-delete-policy": hook-succeeded
  labels:
    app: yunikorn
    release: {{ .Release.Name }}
spec:
  template:
    metadata:
      name: yunikorn-cleanup
      labels:
        app: yunikorn
        release: {{ .Release.Name }}
    spec:
      serviceAccountName: {{ .Values.serviceAccount }}
      containers:
        - name: curl
          image: "{{ .Values.curl_image.repository }}:{{ .Values.curl_image.tag }}"
          imagePullPolicy: {{ .Values.curl_image.pullPolicy }}
          command:
            - /bin/sh
            - -c
            - >
              APISERVER=https://kubernetes.default.svc;
              SERVICEACCOUNT=/var/run/secrets/kubernetes.io/serviceaccount;
              NAMESPACE=$(cat ${SERVICEACCOUNT}/namespace);
              TOKEN=$(cat ${SERVICEACCOUNT}/token);
              CACERT=${SERVICEACCOUNT}/ca.crt;
              curl --cacert ${CACERT} --header "Authorization: Bearer ${TOKEN}" -X DELETE ${APISERVER}/api/v1/namespaces/${NAMESPACE}/configmaps/yunikorn-configs;
              curl --cacert ${CACERT} --header "Authorization: Bearer ${TOKEN}" -X DELETE ${APISERVER}/api/v1/namespaces/${NAMESPACE}/serviceaccounts/yunikorn-admin;
              curl --cacert ${CACERT} --header "Authorization: Bearer ${TOKEN}" -X DELETE ${APISERVER}/apis/rbac.authorization.k8s.io/v1beta1/clusterrolebindings/yunikorn-rbac;
      restartPolicy: Never
