apiVersion: v1
kind: ConfigMap
metadata:
  name: yunikorn-configs
  labels:
    app: yunikorn
    chart: {{ include "yunikorn.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
  annotations:
    "helm.sh/hook": "pre-install"
    "helm.sh/hook-weight": "2"
data:
  queues.yaml: {{quote .Values.configuration}}